### ISSUE TITLE
Getting the following traceback

### ISSUE THREAD

**Issue by slerman12** [MaxStrange/retrowrapper#6] opened 2019-03-07 19:01 UTC
Not sure what's causing this. Each process returns the following error:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/retrowrapper.py", line 37, in _retrocom
    result = result(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/retro/retro_env.py", line 185, in step
    for p, ap in enumerate(self.action_to_array(a)):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/retro/retro_env.py", line 170, in action_to_array
    ap = a[self.num_buttons * p:self.num_buttons * (p + 1)]
TypeError: 'int' object is not subscriptable
```

**Comment by MaxStrange** [comment] 2019-03-07 20:50
Hmm. This error looks like it is originating in retro itself. Retrowrapper is passing through a function call, and the error is stemming from that function call.

Could you post a minimal reproduction of this bug?

**Comment by slerman12** [comment] 2019-03-07 23:06
I'm just trying to run retro on a basic A3C implementation. The A3C implementation is fairly minimal (only one file), so maybe I can link that? The only change I made to it is I added a state space variable since it was using Cartpole and retro has a different state space, and I modified the neural network model to begin with a ConvNet since retro game states are images, unlike the Cartpole example used. The problem might be coming from the action space differences maybe.

Code:
https://github.com/jaromiru/AI-blog/blob/master/CartPole-A3C.py

Explanation of code: 
https://jaromiru.com/2017/03/26/lets-make-an-a3c-implementation/

Do you have an example of retrowrapper running with a parallel RL algorithm like A3C? That's all I was trying to make. Specifically, I was just trying to run SonicTheHedgehog-Genesis with A3C.

I would provide a more minimal example, but the traceback doesn't even tell me where in the A3C code the problem is (it might also help if I could somehow get a longer traceback). I could attach my modified version of this A3C-cartpole implementation, the one throwing the error, if that would help. Or, if you know how to modify this A3C or any A3C to work with retro and could show me, you would be saving me so much.

**Comment by MaxStrange** [comment] 2019-03-08 01:28
Ah, you were basing your code off of CartPole. Gym's actions are scalar values, not lists. Gym-Retro's actions are lists, where each value is either a 0 or a 1. The list contains one value for each button on the controller, and a 1 in the list at index i indicates that button i is pressed.

Does that make sense? So your problem is exactly what you figured, the action spaces are different. You need to modify your code to account for that.

**Comment by MaxStrange** [comment] 2019-03-14 19:22
Closing this now. Feel free to reopen if you feel like your question hasn't been addressed.

**Closed as completed by MaxStrange** 2019-03-14 19:22 UTC
